# Week2 授業前課題3 行列積のスクラッチ  
以下のような行列A、Bを考えます。   
A=  
[-1, 2, 3]  
[4, -5, 6]  
[7, 8, -9]  
B=  
[0, 2, 1]  
[0, 2, -8]  
[2, 9, -1] 

## 【問題1】行列積を手計算する  
>AとBの行列積を手計算で解いてください。  
>計算過程もマークダウンテキストを用いて説明してください。

### 【問題1】 の解答

AB　=  
-1×0 + 2×0 + 3×2,&emsp; -1×2 + 2×2 + 3×9,&emsp; -1×1 + 2×-8 + 3×-1  
4×0 + -5×0 + 6×2,&emsp; 4×2 + -5×2 + 6×9,&emsp; 4×1 + -5×-8 + 6×-1  
7×0 + 8×0 + -9×2,&emsp; 7×2 + 8×2 + -9×9,&emsp; 7×1 + 8×-8 + -9×-1  

答え：  
&nbsp;&nbsp;6&nbsp;&nbsp;&nbsp;29&nbsp;&nbsp;-20  
&nbsp;12&nbsp;&nbsp;&nbsp;52&nbsp;&nbsp;38  
-18&nbsp;-51&nbsp;-48  

## 【問題2】NumPyの関数による計算  
>この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。  
>これらを使い行列積を計算してください。

In [91]:
# np.matmulによる行列積
x_ndarray_matmul = np.matmul(a_ndarray , b_ndarray)

# np.dotによる行列積
x_ndarray_dot = np.dot(a_ndarray , b_ndarray)

# @演算子による行列積
x_ndarray_at = a_ndarray@b_ndarray

# 解答
print("np.matmulによる行列積の結果は：\n{}".format(x_ndarray_matmul))
print("np.dotによる行列積の結果は：\n{}".format(x_ndarray_dot))
print("@演算子による行列積の結果は：\n{}".format(x_ndarray_at))


np.matmulによる行列積の結果は：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
np.dotによる行列積の結果は：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
@演算子による行列積の結果は：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装  
>手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。  
>行列Aの(0,0)の要素 a0,0 と行列Bの(0,0)の要素 b0,0 を掛け合わせる  
>行列Aの(0,1)の要素 a0,1 と行列Bの(1,0)の要素 b1,0 を掛け合わせる  
>行列Aの(0,2)の要素 a0,2 と行列Bの(2,0)の要素 b2,0 を掛け合わせる  
>それらの値を全て足し合わせる  
>
>数式で表すと  
>
>&nbsp;2  
>&nbsp;∑&nbsp;&nbsp;a<sub>0,k</sub>&nbsp;b<sub>k,0</sub>  
>k=0  
>
>です。  
>
>この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [96]:
# 行列Aの行数を入れる変数
a_i = 0
# 行列Bの列数を入れる変数
b_j = 0

# ABの行列積（0,　0）の計算
x_ai0_b0j = a_ndarray[a_i, 0]*b_ndarray[0, b_j]
x_ai1_b1j = a_ndarray[a_i, 1]*b_ndarray[1, b_j]
x_ai2_b2j  = a_ndarray[a_i, 2]*b_ndarray[2, b_j]
x_00 = x_ai0_b0j + x_ai1_b1j + x_ai2_b2j


# 解答
print("numpyの関数を使わずに計算した行列積(0, 0)の結果は：{}".format(x_00))


numpyの関数を使わずに計算した行列積(0, 0)の結果は：6


## 【問題4】行列積を行う関数の作成  
>問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。  
>行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。  
>
>計算結果である 3×3 の行列Cの各要素 ci,j は数式で表すと次のようになります。  
>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2  
>c<sub>i,j</sub>&nbsp;=&nbsp;∑&nbsp;&nbsp;a<sub>i,k</sub>b<sub>k,j</sub>  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;k=0  
>
>for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス i や j を1増やすと、次の行や列に移ることができます。  



In [93]:
import numpy as np


def tensor_calculator(a_ndarray, b_ndarray):
    """
    n行m列の”１から倍ずつ増えていく数列”のndarray（多次元配列）を作成する関数。
    
    Parameteres
    --------------
    a_ndarray:  ndarray（int, float）
        積を求めたい行列
    b_ndarray:  ndarray（int, float）
        積を求めたい行列
        
    Returns
    x_ndarray: ndarray
        計算結果の２次元配列
    --------------
    none
    """
    # 解答用の行列を入れる空リスト作成
    x = []

    # 計算
    for a_i in range(len(a_ndarray[:,0])):
        # １行分の計算結果を入れる空リストを作成
        x_row = []
        # 内積
        for b_j in range(len(b_ndarray[0,:])):
            x_0j = a_ndarray[a_i, 0]*b_ndarray[0, b_j]
            x_1j = a_ndarray[a_i, 1]*b_ndarray[1, b_j]
            x_2j = a_ndarray[a_i, 2]*b_ndarray[2, b_j]
            x_row.append(x_0j + x_1j + x_2j)
        # １行分の計算が終わったので、解答用のリストに入れる
        x.append(x_row)

    # numpyのndarrayに変換
    x_ndarray = np.array(x)
    
    return x_ndarray


# 計算したい配列を定義
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 作成したtensor_calculator関数で行列積を計算
x_ndarray = tensor_calculator(a_ndarray, b_ndarray)

# 解答
print("numpy関数を使わないスクラッチによる行列積の結果は：\n{}".format(x_ndarray))


numpy関数を使わないスクラッチによる行列積の結果は：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題5】計算が定義されない入力を判定する  

>問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。  
>if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [94]:
import numpy as np


def tensor_calculator(a_ndarray, b_ndarray):
    """
    n行m列の”１から倍ずつ増えていく数列”のndarray（多次元配列）を作成する関数。
    
    Parameteres
    --------------
    a_ndarray:  ndarray（int, float）
        積を求めたい行列（かけられる側）
    b_ndarray:  ndarray（int, float）
        積を求めたい行列（かける側）
        
    Returns
    x_ndarray: ndarray
        計算結果の２次元配列
    --------------
    none
    """
    # 計算実行判定用配列
    avoid_calculation = False
    
    # 計算可能か判定するために行列サイズ取得
    a_column_count = len(a_ndarray[0,:])
    b_row_count = len(b_ndarray[:,0])
    
    #　 かけられる側の列数とかける側の行数が等しいかチェック
    if a_column_count != b_row_count:
        avoid_calculation = True
    
    # 入力された行列が計算可能な形状ならば計算実施
    if not avoid_calculation:
        # 解答用の行列を入れる空リスト作成
        x = []

        # 計算
        for a_i in range(len(a_ndarray[:,0])):
            # １行分の計算結果を入れる空リストを作成
            x_row = []
            # 内積
            for b_j in range(len(b_ndarray[0,:])):
                x_0j = a_ndarray[a_i, 0]*b_ndarray[0, b_j]
                x_1j = a_ndarray[a_i, 1]*b_ndarray[1, b_j]
                x_2j = a_ndarray[a_i, 2]*b_ndarray[2, b_j]
                x_row.append(x_0j + x_1j + x_2j)
            # １行分の計算が終わったので、解答用のリストに入れる
            x.append(x_row)

        # numpyのndarrayに変換
        x_ndarray = np.array(x)

        return x_ndarray
                      
    else:
        print("ERROR : かけられる側の列数とかける側の行数が等しくありません。")


# 計算したい配列を定義
# a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
# b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# 作成したtensor_calculator関数で行列積を計算
x_ndarray = tensor_calculator(d_ndarray, e_ndarray)

# 解答
print("numpy関数を使わないスクラッチによる行列積の結果は：\n{}".format(x_ndarray))

ERROR : かけられる側の列数とかける側の行数が等しくありません。
numpy関数を使わないスクラッチによる行列積の結果は：
None


## 【問題6】転置  
>片方の行列を転置することで、行列積が計算できるようになります。  
>np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [1]:
import numpy as np


def tensor_calculator(a_ndarray, b_ndarray):
    """
    n行m列の”１から倍ずつ増えていく数列”のndarray（多次元配列）を作成する関数。
    
    Parameteres
    --------------
    a_ndarray:  ndarray（int, float）
        積を求めたい行列（かけられる側）
    b_ndarray:  ndarray（int, float）
        積を求めたい行列（かける側）
        
    Returns
    x_ndarray: ndarray
        計算結果の２次元配列
    --------------
    none
    """
    # 計算実行判定用配列
    avoid_calculation = False
    
    # 計算可能か判定するために行列サイズ取得
    a_column_count = len(a_ndarray[0,:])
    b_row_count = len(b_ndarray[:,0])
    b_column_count = len(b_ndarray[0,:])
    
    #　 かけられる側の列数とかける側の行数が等しいかチェック
    if a_column_count != b_row_count:
        if  a_column_count == b_column_count:
            b_ndarray = b_ndarray.T
            print("WARNING : 行列が転置されました。")
        else:
            avoid_calculation = True
    
    # 入力された行列が計算可能な形状ならば計算実施
    if not avoid_calculation:
        # 解答用の行列を入れる空リスト作成
        x = []

        # 計算
        for a_i in range(len(a_ndarray[:,0])):
            # １行分の計算結果を入れる空リストを作成
            x_row = []
            # 内積
            for b_j in range(len(b_ndarray[0,:])):
                x_0j = a_ndarray[a_i, 0]*b_ndarray[0, b_j]
                x_1j = a_ndarray[a_i, 1]*b_ndarray[1, b_j]
                x_2j = a_ndarray[a_i, 2]*b_ndarray[2, b_j]
                x_row.append(x_0j + x_1j + x_2j)
            # １行分の計算が終わったので、解答用のリストに入れる
            x.append(x_row)

        # numpyのndarrayに変換
        x_ndarray = np.array(x)

        return x_ndarray
                      
    else:
        print("ERROR : かけられる側の列数とかける側の行数が等しくありません。")


# 計算したい配列を定義
# a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
# b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# 作成したtensor_calculator関数で行列積を計算
x_ndarray = tensor_calculator(d_ndarray, e_ndarray)

# 解答
print("numpy関数を使わないスクラッチによる行列積の結果は：\n{}".format(x_ndarray))

numpy関数を使わないスクラッチによる行列積の結果は：
[[ 46  -4]
 [-34  73]]
